# Generated by Django 3.0.5 on 2020-04-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='good',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
